clean: Yes
objc: No
author: Stefan van den Oord
author_url: https://github.com/svdo
github_url: https://github.com/svdo/swift-RichText
github_file_prefix: https://github.com/svdo/swift-RichText/tree/master
module: RichString
module_version: 2.2.1
readme: README.md
copyright: Copyright © 2016 [Stefan van den Oord](https://github.com/svdo). All rights reserved
